# This playbook configures the docker instance

- hosts: "{{ hosts }}"
  tasks:
    - name: start ansible
      debug: msg="ansible will start to configure this docker instance"

    - include: couchdb.yml
      vars:
        couchdb_dir: "/var/run/couchdb/"
        seal_couch_dir: "/seal/couchdb/"

    - include: apollo.yml
      vars:
        version: 1.7

    - include: caat.yml
      vars:
        version: 3.15.0-20140807
