# This playbook configures the docker instance

- hosts: "{{ hosts }}"
  tasks:
    - name: start ansible
      debug: msg="ansible will start to configure this docker instance"

    - include: caat.yml

